/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    journey: Journey;
    'academic-records': AcademicRecord;
    events: Event;
    'medical-camps': MedicalCamp;
    community: Community;
    achievements: Achievement;
    certificates: Certificate;
    research: Research;
    gallery: Gallery;
    journal: Journal;
    documents: Document;
    media: Media;
    categories: Category;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    journey: JourneySelect<false> | JourneySelect<true>;
    'academic-records': AcademicRecordsSelect<false> | AcademicRecordsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'medical-camps': MedicalCampsSelect<false> | MedicalCampsSelect<true>;
    community: CommunitySelect<false> | CommunitySelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    journal: JournalSelect<false> | JournalSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'page-texts': PageText;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'page-texts': PageTextsSelect<false> | PageTextsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Each year of MBBS, then the house job, specialization and career. Records with a matching year appear on that stage's page automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey".
 */
export interface Journey {
  id: number;
  title: string;
  /**
   * e.g. 2026, 2030–31, Future
   */
  periodLabel: string;
  /**
   * Records dated in this year are listed on this stage. Leave empty for future stages.
   */
  year?: number | null;
  phase?: ('mbbs' | 'house-job' | 'clinical' | 'specialization' | 'residency' | 'career') | null;
  /**
   * Short line for the home-page timeline, e.g. “MBBS Begins”.
   */
  headline?: string | null;
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  subjects?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  milestones?:
    | {
        /**
         * e.g. March 2026
         */
        when?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cover?: (number | null) | Media;
  progress?: ('auto' | 'completed' | 'current' | 'upcoming') | null;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  /**
   * Used in the page address. Leave empty to create it from the periodLabel.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos, videos and PDFs. Upload once, then pick them from any record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the file shows, e.g. “Orientation day, CPMC”. Read aloud by screen readers.
   */
  alt: string;
  caption?: string | null;
  takenOn?: string | null;
  /**
   * Private files are never shown on the website. Note: when files are stored on Vercel Blob, anyone with a file's exact link can still open it.
   */
  visibility: 'public' | 'private';
  showsPatients?: boolean | null;
  /**
   * Files showing patients are kept private until consent is recorded.
   */
  consentObtained?: boolean | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Exams, results, academic milestones, courses and presentations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-records".
 */
export interface AcademicRecord {
  id: number;
  title: string;
  type: 'exam' | 'result' | 'milestone' | 'course' | 'presentation' | 'skill' | 'other';
  date?: string | null;
  subject?: string | null;
  /**
   * Grade, marks or position.
   */
  result?: string | null;
  showResult?: boolean | null;
  description?: string | null;
  attachments?: (number | Media)[] | null;
  /**
   * Which year of the journey this belongs to. Filled in from the date automatically.
   */
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * College events, seminars, workshops, conferences, sports and more. Events with a future date appear as upcoming; past events move to the archive automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  date: string;
  endDate?: string | null;
  location?: string | null;
  role?: string | null;
  /**
   * One or two sentences shown in lists.
   */
  summary?: string | null;
  /**
   * The full story, shown on the event's page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (number | null) | Media;
  photos?: (number | Media)[] | null;
  /**
   * A YouTube or other video link.
   */
  videoUrl?: string | null;
  videoFile?: (number | null) | Media;
  /**
   * Certificates received at this event. Add the certificate under Achievements → Certificates first.
   */
  certificates?: (number | Certificate)[] | null;
  /**
   * Manage the list under Settings → Categories.
   */
  category?: (number | null) | Category;
  featured?: boolean | null;
  /**
   * Used in the page address. Leave empty to create it from the title.
   */
  slug?: string | null;
  /**
   * Which year of the journey this belongs to. Filled in from the date automatically.
   */
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upload a photo of the certificate (shown on the website) and the original PDF. Mark it private to keep it only in the admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  title: string;
  issuer?: string | null;
  date?: string | null;
  course?: string | null;
  description?: string | null;
  preview?: (number | null) | Media;
  file?: (number | null) | Media;
  /**
   * The event where this certificate was received.
   */
  event?: (number | null) | Event;
  /**
   * Manage the list under Settings → Categories.
   */
  category?: (number | null) | Category;
  visibility: 'public' | 'private';
  /**
   * Used in the page address. Leave empty to create it from the title.
   */
  slug?: string | null;
  /**
   * Which year of the journey this belongs to. Filled in from the date automatically.
   */
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The categories used to organise events, certificates, achievements and the gallery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  section: 'events' | 'certificates' | 'achievements' | 'gallery';
  description?: string | null;
  /**
   * Events in this category (workshops, seminars, conferences…) are listed on the Academic page and counted as “Workshops & Seminars”.
   */
  academic?: boolean | null;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  /**
   * Used in the page address. Leave empty to create it from the title.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The Annual Free Medical Camp — one record per year. Impact totals on the website are calculated from these records.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-camps".
 */
export interface MedicalCamp {
  id: number;
  year: number;
  edition: number;
  campStatus?: ('planned' | 'held') | null;
  /**
   * Leave empty to use the series title from Page texts → Medical camps, followed by the year.
   */
  title?: string | null;
  date?: string | null;
  location?: string | null;
  organizedBy?: string | null;
  team?:
    | {
        name: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  awareness?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  medicinesSupport?: string | null;
  sponsors?:
    | {
        name: string;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  summary?: string | null;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  patientsServed?: number | null;
  doctors?: number | null;
  volunteers?: number | null;
  /**
   * Only verified numbers are shown on the website and counted in totals.
   */
  numbersVerified?: boolean | null;
  photos?: (number | Media)[] | null;
  /**
   * A YouTube or other video link.
   */
  videoUrl?: string | null;
  videoFile?: (number | null) | Media;
  certificate?: (number | null) | Media;
  report?: (number | null) | Media;
  /**
   * Never enter patient names, CNIC numbers, phone numbers, medical records or reports. Photos and videos are shown on the website only when both boxes are ticked.
   */
  privacy?: {
    mediaConsent?: boolean | null;
    publicDisplayApproved?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Blood donation, health awareness, outreach, patient welfare and volunteer work. (The Annual Free Medical Camp has its own section.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community".
 */
export interface Community {
  id: number;
  title: string;
  type: 'medical-camp' | 'blood-donation' | 'health-awareness' | 'outreach' | 'patient-welfare' | 'volunteer';
  date?: string | null;
  location?: string | null;
  role?: string | null;
  organizer?: string | null;
  services?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  supporters?: string | null;
  /**
   * One or two sentences shown in lists.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  peopleServed?: number | null;
  doctors?: number | null;
  volunteers?: number | null;
  /**
   * Only verified numbers are shown on the website and counted in totals.
   */
  numbersVerified?: boolean | null;
  /**
   * Never enter patient names, CNIC numbers, phone numbers, medical records or reports. Photos and videos are shown on the website only when both boxes are ticked.
   */
  privacy?: {
    mediaConsent?: boolean | null;
    publicDisplayApproved?: boolean | null;
  };
  photos?: (number | Media)[] | null;
  /**
   * A YouTube or other video link.
   */
  videoUrl?: string | null;
  videoFile?: (number | null) | Media;
  certificate?: (number | null) | Media;
  report?: (number | null) | Media;
  /**
   * Used in the page address. Leave empty to create it from the title.
   */
  slug?: string | null;
  /**
   * Which year of the journey this belongs to. Filled in from the date automatically.
   */
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Awards, positions, distinctions and other milestones.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  title: string;
  date?: string | null;
  awardedBy?: string | null;
  summary?: string | null;
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  certificate?: (number | null) | Certificate;
  event?: (number | null) | Event;
  /**
   * Manage the list under Settings → Categories.
   */
  category?: (number | null) | Category;
  /**
   * Used in the page address. Leave empty to create it from the title.
   */
  slug?: string | null;
  /**
   * Which year of the journey this belongs to. Filled in from the date automatically.
   */
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: number;
  title: string;
  type: 'project' | 'case-report' | 'poster' | 'presentation' | 'publication' | 'conference';
  researchStatus?: ('ongoing' | 'completed' | 'presented' | 'published') | null;
  date?: string | null;
  role?: string | null;
  institution?: string | null;
  area?: string | null;
  /**
   * One or two sentences shown in lists.
   */
  summary?: string | null;
  abstract?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  authors?: string | null;
  venue?: string | null;
  doi?: string | null;
  link?: string | null;
  pdf?: (number | null) | Media;
  /**
   * Used in the page address. Leave empty to create it from the title.
   */
  slug?: string | null;
  /**
   * Which year of the journey this belongs to. Filled in from the date automatically.
   */
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photo albums. Upload many photos at once with the Photos field.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  date?: string | null;
  description?: string | null;
  photos: (number | Media)[];
  /**
   * Manage the list under Settings → Categories.
   */
  category?: (number | null) | Category;
  /**
   * Used in the page address. Leave empty to create it from the title.
   */
  slug?: string | null;
  /**
   * Which year of the journey this belongs to. Filled in from the date automatically.
   */
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reflections and stories. A note that posts aren't medical advice is added to every post automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal".
 */
export interface Journal {
  id: number;
  title: string;
  date: string;
  topic?: ('learning' | 'research' | 'conference' | 'community' | 'awareness' | 'academic' | 'professional') | null;
  excerpt?: string | null;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Used in the page address. Leave empty to create it from the title.
   */
  slug?: string | null;
  /**
   * Which year of the journey this belongs to. Filled in from the date automatically.
   */
  year?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * CV, papers, reports and other documents. Private documents are kept for the record and never shown on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  type: 'cv' | 'certificate' | 'research-paper' | 'report' | 'presentation' | 'conference' | 'award' | 'other';
  date?: string | null;
  description?: string | null;
  file: number | Media;
  visibility: 'public' | 'private';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'journey';
        value: number | Journey;
      } | null)
    | ({
        relationTo: 'academic-records';
        value: number | AcademicRecord;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'medical-camps';
        value: number | MedicalCamp;
      } | null)
    | ({
        relationTo: 'community';
        value: number | Community;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'research';
        value: number | Research;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'journal';
        value: number | Journal;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey_select".
 */
export interface JourneySelect<T extends boolean = true> {
  title?: T;
  periodLabel?: T;
  year?: T;
  phase?: T;
  headline?: T;
  summary?: T;
  content?: T;
  subjects?:
    | T
    | {
        name?: T;
        id?: T;
      };
  milestones?:
    | T
    | {
        when?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  cover?: T;
  progress?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-records_select".
 */
export interface AcademicRecordsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  subject?: T;
  result?: T;
  showResult?: T;
  description?: T;
  attachments?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  endDate?: T;
  location?: T;
  role?: T;
  summary?: T;
  description?: T;
  cover?: T;
  photos?: T;
  videoUrl?: T;
  videoFile?: T;
  certificates?: T;
  category?: T;
  featured?: T;
  slug?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-camps_select".
 */
export interface MedicalCampsSelect<T extends boolean = true> {
  year?: T;
  edition?: T;
  campStatus?: T;
  title?: T;
  date?: T;
  location?: T;
  organizedBy?: T;
  team?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  services?:
    | T
    | {
        name?: T;
        id?: T;
      };
  awareness?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  medicinesSupport?: T;
  sponsors?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  summary?: T;
  story?: T;
  patientsServed?: T;
  doctors?: T;
  volunteers?: T;
  numbersVerified?: T;
  photos?: T;
  videoUrl?: T;
  videoFile?: T;
  certificate?: T;
  report?: T;
  privacy?:
    | T
    | {
        mediaConsent?: T;
        publicDisplayApproved?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community_select".
 */
export interface CommunitySelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  location?: T;
  role?: T;
  organizer?: T;
  services?:
    | T
    | {
        name?: T;
        id?: T;
      };
  supporters?: T;
  summary?: T;
  description?: T;
  peopleServed?: T;
  doctors?: T;
  volunteers?: T;
  numbersVerified?: T;
  privacy?:
    | T
    | {
        mediaConsent?: T;
        publicDisplayApproved?: T;
      };
  photos?: T;
  videoUrl?: T;
  videoFile?: T;
  certificate?: T;
  report?: T;
  slug?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  awardedBy?: T;
  summary?: T;
  details?: T;
  image?: T;
  certificate?: T;
  event?: T;
  category?: T;
  slug?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  title?: T;
  issuer?: T;
  date?: T;
  course?: T;
  description?: T;
  preview?: T;
  file?: T;
  event?: T;
  category?: T;
  visibility?: T;
  slug?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  researchStatus?: T;
  date?: T;
  role?: T;
  institution?: T;
  area?: T;
  summary?: T;
  abstract?: T;
  authors?: T;
  venue?: T;
  doi?: T;
  link?: T;
  pdf?: T;
  slug?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  date?: T;
  description?: T;
  photos?: T;
  category?: T;
  slug?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal_select".
 */
export interface JournalSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  topic?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  slug?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  date?: T;
  description?: T;
  file?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  takenOn?: T;
  visibility?: T;
  showsPatients?: T;
  consentObtained?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  section?: T;
  description?: T;
  academic?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * e.g. Dr. (empty while a student)
   */
  prefix?: string | null;
  name: string;
  /**
   * e.g. MBBS
   */
  postNominals?: string | null;
  role?: string | null;
  /**
   * Shown after the role, e.g. MBBS Student | Aspiring Physician
   */
  roleSubtitle?: string | null;
  institution?: string | null;
  institutionShort?: string | null;
  city?: string | null;
  tagline?: string | null;
  /**
   * Journey stages before this year show as completed, this year as in progress, later years as upcoming.
   */
  currentYear: number;
  email?: string | null;
  website?: string | null;
  linkedin?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Drag to reorder. Remove an item to hide it.
   */
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerNote?: string | null;
  /**
   * Visitors can still switch with the button in the header.
   */
  defaultTheme?: ('light' | 'dark') | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  shareImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  statement?: string | null;
  portrait?: (number | null) | Media;
  buttons?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        title: string;
        href?: string | null;
        icon?:
          ('graduation' | 'book' | 'community' | 'research' | 'stethoscope' | 'heart' | 'award' | 'calendar') | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  showTimeline?: boolean | null;
  showImpact?: boolean | null;
  showCamp?: boolean | null;
  showUpcoming?: boolean | null;
  showLatest?: boolean | null;
  timelineTitle?: string | null;
  impactTitle?: string | null;
  campTitle?: string | null;
  upcomingTitle?: string | null;
  latestTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  introduction?: string | null;
  positioning?: string | null;
  portrait?: (number | null) | Media;
  education?:
    | {
        title: string;
        institution?: string | null;
        period?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  interests?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  researchInterests?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        title: string;
        level?: string | null;
        id?: string | null;
      }[]
    | null;
  values?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  communityVision?: string | null;
  careerGoals?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Headings and introductions for each section page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-texts".
 */
export interface PageText {
  id: number;
  journey?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  academic?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  research?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  community?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  camps?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
    /**
     * Used for each camp that has no title of its own.
     */
    seriesTitle?: string | null;
  };
  events?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  achievements?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  certificates?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  gallery?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  journal?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
    disclaimer?: string | null;
  };
  cv?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
  };
  contact?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
    note?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  prefix?: T;
  name?: T;
  postNominals?: T;
  role?: T;
  roleSubtitle?: T;
  institution?: T;
  institutionShort?: T;
  city?: T;
  tagline?: T;
  currentYear?: T;
  email?: T;
  website?: T;
  linkedin?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerNote?: T;
  defaultTheme?: T;
  metaTitle?: T;
  metaDescription?: T;
  shareImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  statement?: T;
  portrait?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        href?: T;
        icon?: T;
        text?: T;
        id?: T;
      };
  showTimeline?: T;
  showImpact?: T;
  showCamp?: T;
  showUpcoming?: T;
  showLatest?: T;
  timelineTitle?: T;
  impactTitle?: T;
  campTitle?: T;
  upcomingTitle?: T;
  latestTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  introduction?: T;
  positioning?: T;
  portrait?: T;
  education?:
    | T
    | {
        title?: T;
        institution?: T;
        period?: T;
        description?: T;
        id?: T;
      };
  interests?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  researchInterests?:
    | T
    | {
        title?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        title?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        title?: T;
        level?: T;
        id?: T;
      };
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  communityVision?: T;
  careerGoals?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-texts_select".
 */
export interface PageTextsSelect<T extends boolean = true> {
  journey?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  academic?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  research?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  community?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  camps?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        seriesTitle?: T;
      };
  events?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  achievements?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  certificates?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  gallery?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  journal?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        disclaimer?: T;
      };
  cv?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}